server:
  port: 8080
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/framework
          username: root
          password: 123456

# 开启Swagger的Basic认证功能,默认是false
knife4j:
  enable: true
  basic:
    enable: true # Basic认证用户名
    username: admin # Basic认证密码
    password: 123456

easy-es:
  enable: true
  address: 127.0.0.1:9200
  global-config:
    print-dsl: false
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 配置文件服务器
gofastdfs:
  config:
    # 文件服务器的服务地址
    ip: http://127.0.0.1
    # 文件服务的服务端口（默认为8080，可修改）
    port: 30010
    # 文件服务器的组名
    group: group1
    # 文件服务器的场景（配置之后会自动创建，上传的文件都会存放到这个场景下）
    scene: demo